[package]
name = "alice-sys"
version = "0.1.0"
authors = ["cbourjau <christian.bourjau@cern.ch>"]
build = "build.rs"

[dependencies]
libc = "*"
alice-open-data = { path="../alice-open-data" }
[build-dependencies]
gcc = "0.3"
bindgen = "^0.29.0"
